### ISSUE TITLE
Ao alterar o texto de "Linhas por página" o grid não é atualizado

### ISSUE THREAD

**Issue by lrsjunior** [afpop/softgrid#2]
Quando digitamos um valor diretamente no campo de texto das "Linhas por página" o grid não atualiza os registros. É atualizado apenas quando clicamos pelos controles "+" e "-".
![linhas](https://user-images.githubusercontent.com/32581145/31295905-b92091c2-aab6-11e7-9a41-afd8611a8758.png)

**Comment by joaopop5** [comment]
Bug corrigido a partir da v1.1.2
