### ISSUE TITLE
Botões "Próxima Página" e "Página Anterior"

### ISSUE THREAD

**Issue by lrsjunior** [afpop/softgrid#3]
Os botões no "Próxima Página" e "Página Anterior" no "footer" do grid não estão trocando as páginas com o clique do usuário.
![botoes](https://user-images.githubusercontent.com/32581145/32182757-98478f66-bd7e-11e7-8bd4-d7d2f501f960.png)

**Comment by joaopop5** [comment]
Bug corrigido a partir da v1.0.4.
